### PR TITLE
Adding submodules

### PR DESCRIPTION
**Pull request by fao89**
- pulpcore
- pulp_file
- pulp-certguard
- pulp_installer

https://pulp.plan.io/issues/6959

### CODE REVIEW

**Comment by mdellweg** [comment]
I think the master branch should follow the corresponding default branches of the submodules.

**Comment by mdellweg** [comment]
Thinking a bit more about this, do you think, we should have the submodules collected in a subfolder (maybe `plugins`)?
I know we could move them later, but with submodules that _is_ rather painful.

**Comment by fao89** [comment]
> Thinking a bit more about this, do you think, we should have the submodules collected in a subfolder (maybe `plugins`)?
> I know we could move them later, but with submodules that _is_ rather painful.

I think we can have a subfolder, but in this case, pulpcore and pulp_installer are not plugins.
So, do you think only the plugins should go to the subfolder? Or do we have to think in another name for the subfolder?

**Comment by mdellweg** [comment]
@dkliban any suggestion on a name?

**Pull request closed without merging**
